### ISSUE TITLE
Create Find support page (epic)

### ISSUE THREAD

**Issue by dupreesi** [techforbetter/myPickle#22]
As a user/ support provider I want to be able to see a pre-selected ‚support providers‘ page that 
- [ ] shows me a ‚see all‘ link redirecting me to an ‚all support provider results‘ page
- [ ] shows me a selection of results (sorted by date of profile creation)
- [ ] selection should be scrollable 
- [ ] each result should include: 
- Profile picture
- Wellness area
- Location (city name)
- Type of service 
- „View more“ link redirecting to profile page

As a user/ support provider I want to be able to see a pre-selected ‚blog posts‘ page that
- [ ] shows me a ‚see all‘ link redirecting me to an ‚all blog post results‘ page
- [ ] headline of blog posts
- [ ] wellness area 
- [ ] more categories???

![bildschirmfoto 2018-12-10 um 17 16 42](https://user-images.githubusercontent.com/23721486/49749168-823f8280-fc9f-11e8-8dfa-594ae8fae01c.png)
