### ISSUE TITLE
Create sign-up process 

### ISSUE THREAD

**Issue by dupreesi** [techforbetter/myPickle#23]
# Please create separate issues for each headline of the user journey and relate them to this epic #23
## Pre-sign-up page  
As a support provider I want to 
- [x] see a introduction screen (‚Welcome to my pickle‘ that explains the sign-up process)
- [x] Click on a continue button that redirects me to the sign-up form
- [x] Shows me an email address I can contact in case I have any questions
![bildschirmfoto 2018-12-10 um 17 21 35](https://user-images.githubusercontent.com/23721486/49749404-20334d00-fca0-11e8-8003-bd1925c1fee5.png)

## Area of wellness support
- [x] As a support provider I would like to see a ‚select your wellness area page’ offering me 8 checkboxes (options: emotional, social, physical, financial, spiritual, intellectual, environmental, occupational)
- [x] I can select multiple options 
- [x] selecting at least one is required
- [x] I can click a next button that redirects me to the next sign up process page
- [x] if I did not select an option I get a prompt that says that I have to select an option in order to continue
![bildschirmfoto 2018-12-10 um 17 21 49](https://user-images.githubusercontent.com/23721486/49749419-26292e00-fca0-11e8-8c8a-a9297c2f9d4f.png)

## User Details Page (all fields are required!)
- [x] As a support provider I would like to start the sign up process entering my core details 
- Contact name
- Contact Email
- Password (to be hashed)
- Confirm Password
- Contact Tel
- Contact Address

## Admin Info (same page as user details, all fields are required)
- Company number
- Registered Office address
- Registrations memberships

- [x] I can hit a submit (next) button 
- [x] form validation error messages
- [x] if I did not fill in a field I get an error message saying that this field is required
- [x] if my password is less than 6 characters or if passwords don’t match I get an error message
- [ ] if my email address is already stored in the database I get an error message (‚user already exists‘)
![bildschirmfoto 2018-12-10 um 17 24 15](https://user-images.githubusercontent.com/23721486/49749518-7607f500-fca0-11e8-9203-9965e6c98d2c.png)
![bildschirmfoto 2018-12-10 um 17 24 21](https://user-images.githubusercontent.com/23721486/49749526-7bfdd600-fca0-11e8-9c8e-feecff9bbed2.png)

## Basic Info form
- [x] as a service provider I can see a page that asks me to fill in form fields so I can create my initial profile 
- [x] Please select your type of Support (here we select therapist or others, required)!
- [x] name organisation
- [x] url
- [x] Photo or logo
- [x] Short description

- [ ] create profile button creating success popup (‚Profile created‘) including 2 buttons
- [ ] Add to profile btn: redirection to edit profile page
- [ ] Skip btn: redirection to dashboard
- [x] if errors -> form validation incl. error messages
![bildschirmfoto 2018-12-10 um 17 26 35](https://user-images.githubusercontent.com/23721486/49749677-caab7000-fca0-11e8-92a3-510e1391b20b.png)
![bildschirmfoto 2018-12-10 um 17 26 39](https://user-images.githubusercontent.com/23721486/49749686-cf702400-fca0-11e8-8e2c-c14203d1b776.png)
![bildschirmfoto 2018-12-10 um 17 41 27](https://user-images.githubusercontent.com/23721486/49750477-e283f380-fca2-11e8-8257-75122228e2b3.png)

**Comment by thejoefriel** [comment]
List of questions with options, helper text etc for the database attached: 
[Sign-up-form-modified-for-DB.xlsx](https://github.com/techforbetter/myPickle/files/2668262/Sign-up-form-modified-for-DB.xlsx)
